version: "2"
services:
  app:
    build: .
    container_name: "${APP_NAME}-app"
    environment: 
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      REDIS_HOST: redis
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_CACHE_DB: 1
      REDIS_CLIENT: predis
      ELASTICSEARCH_HOST: elastic
      ELASTICSEARCH_PORT: 9200
      ELASTICQUENT_DEFAULT_INDEX: "${ELASTICQUENT_DEFAULT_INDEX}"
      QUEUE_CONNECTION: rabbitmq
      RABBITMQ_QUEUE: default
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
      MAIL_MAILER: "${MAIL_MAILER}"
      MAIL_HOST: "${MAIL_HOST}"
      MAIL_PORT: "${MAIL_PORT}"
      MAIL_ENCRYPTION: "${MAIL_ENCRYPTION}"
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      MAIL_FROM_ADDRESS: "${MAIL_FROM_ADDRESS}"
      MAIL_FROM_NAME: "${MAIL_FROM_NAME}"
    depends_on:
     - db
    links:
     - db
    networks:
      - apps
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
  db:
    container_name: "${APP_NAME}-postgres"
    image: postgres
    ports:
      - 8001:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - apps
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
     - "6382:6379"
    networks:
     - apps
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: "${APP_NAME}-elastic"
    environment:
      - node.name=elastic
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
       - ./redis-data:/var/lib/redis/data
    ports:
      - 9200:9200
    networks:
      - apps
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "${APP_NAME}-rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq-data:/var/lib/rabbitmq/data
        - ./rabbitmq-data:/var/lib/rabbitmq/data/vendor
    networks:
        - apps
networks:
  apps:
